### PR TITLE
Draft Idea for the Jobs System

### PR DESCRIPTION
**Pull request by sampoder**
@maxwofford thoughts?

### CODE REVIEW

**Comment by sampoder** [comment]
It works by pulling from https://github.com/hackclub/jobs/tree/main/directory, now this means we lose a bit of the customisability for each page but it it brings everything together

**Comment by lachlanjc** [comment]
#### 📝 Changed routes:


| [**/jobs/\[job\]**](https://v3-qb1hyb0co.hackclub.dev/jobs/[job]) | [**/jobs/bank-ops-associate**](https://v3-qb1hyb0co.hackclub.dev/jobs/bank-ops-associate) |
|:-:|:-:|
|<a href="https://v3-qb1hyb0co.hackclub.dev/jobs/[job]">Screenshot of /jobs/[job]</a><br /><sup><a href="https://images.weserv.nl?url=https://sjc.microlink.io/1AIhUg2oJb9NDOM99TTlToHq107sB6C4-e-bEnnKMOIllEMKc2CTuai9_9wOqFdF8QPh69d9PRKxLEqAIld3hg.png">(view full size)</a> |<a href="https://v3-qb1hyb0co.hackclub.dev/jobs/bank-ops-associate">Screenshot of /jobs/bank-ops-associate</a><br /><sup><a href="https://images.weserv.nl?url=https://sjc.microlink.io/SH-m3BsEp57tImwEuk3LuGo9ir2vQjZZTE2EjqmPx6Gf_lY0jx7ZksD1SCnCzUcOsfFmjacvZ1e4OpXFOUilJQ.png">(view full size)</a> |



| [**/jobs/bank-ops-lead**](https://v3-qb1hyb0co.hackclub.dev/jobs/bank-ops-lead) | [**/jobs/bank-tech-lead**](https://v3-qb1hyb0co.hackclub.dev/jobs/bank-tech-lead) |
|:-:|:-:|
|<a href="https://v3-qb1hyb0co.hackclub.dev/jobs/bank-ops-lead">Screenshot of /jobs/bank-ops-lead</a><br /><sup><a href="https://images.weserv.nl?url=https://sjc.microlink.io/fekhA955HV90stAIQimFGCiuNft8tCMnVS93T-VBKXcUSOgalwVbwJ5Yw_Voo01JaaWLWcB5LiOb1zFx-AhAXw.png">(view full size)</a> |<a href="https://v3-qb1hyb0co.hackclub.dev/jobs/bank-tech-lead">Screenshot of /jobs/bank-tech-lead</a><br /><sup><a href="https://images.weserv.nl?url=https://sjc.microlink.io/RL63Iqgph1gjG5EP_B5G_8oZ41JgWhuT6eJEBSUGhkTwGJxGCD93V-gb2aBgqT3s1zeEiG6-ujx6cufCOUfcmQ.png">(view full size)</a> |



| [**/jobs/brand-director**](https://v3-qb1hyb0co.hackclub.dev/jobs/brand-director) | [**/jobs/clubs-lead**](https://v3-qb1hyb0co.hackclub.dev/jobs/clubs-lead) |
|:-:|:-:|
|<a href="https://v3-qb1hyb0co.hackclub.dev/jobs/brand-director">Screenshot of /jobs/brand-director</a><br /><sup><a href="https://images.weserv.nl?url=https://sjc.microlink.io/Ku3AUVAZC_mf5q7GCoZQ7PIaPkHpUJ3hNVIEzJYH38HtUL68g2g1ZRufEmKlLExZF55U1DFgznTvzcfdLo6B3Q.png">(view full size)</a> |<a href="https://v3-qb1hyb0co.hackclub.dev/jobs/clubs-lead">Screenshot of /jobs/clubs-lead</a><br /><sup><a href="https://images.weserv.nl?url=https://sjc.microlink.io/aJsHkoXl6mZMCEz1wefVFaTNCQMb0UQfLyGhwYi1nMBZs_3SRsaP5BIKJqpQaXQlbame6ILdltlDOExknKoxQg.png">(view full size)</a> |



And 7 other routes:
- [**/jobs/communications-manager**](https://v3-qb1hyb0co.hackclub.dev/jobs/communications-manager)
- [**/jobs/education-engineer**](https://v3-qb1hyb0co.hackclub.dev/jobs/education-engineer)
- [**/jobs/events-designer**](https://v3-qb1hyb0co.hackclub.dev/jobs/events-designer)
- [**/jobs/executive-assistant**](https://v3-qb1hyb0co.hackclub.dev/jobs/executive-assistant)
- [**/jobs**](https://v3-qb1hyb0co.hackclub.dev/jobs)
- [**/jobs/journalist**](https://v3-qb1hyb0co.hackclub.dev/jobs/journalist)
- [**/jobs/philanthropy-position**](https://v3-qb1hyb0co.hackclub.dev/jobs/philanthropy-position)



Commit 121ace56ba70377e2060ecc2a31ffbcab69c6689 (https://v3-qb1hyb0co.hackclub.dev).

**Comment by maxwofford** [comment]
@abbyfischler thoughts on this? Seems like you'll be making most of the edits to jobs positions. Would you like editing like this (just markdown files), or would you need more customization then what markdown can provide?

One note: I really liked how customized https://hackclub.com/jobs/events-designer/ is/was. Maybe we can have the site initially try routing to a customized page, but if it can't find one it looks for a markdown file?

**Comment by sampoder** [comment]
Closing due to conflicts

**Pull request closed without merging**
