### PR TITLE
Add Bank application form

### PR DESCRIPTION
**Pull request by exu3**
Screen Shot 2022-01-30 at 7 59 23 PM
This PR adds a styled Bank application form (replaces the default Airtable form).

### CODE REVIEW

**Comment by lachlanjc** [comment]
#### 📝 Changed routes:


| [**/bank/apply**](https://v3-oodkjhcf5.hackclub.dev/bank/apply) | [**/bank**](https://v3-oodkjhcf5.hackclub.dev/bank) |
|:-:|:-:|
|<a href="https://v3-oodkjhcf5.hackclub.dev/bank/apply">Screenshot of /bank/apply</a><br /><sup><a href="https://images.weserv.nl?url=https://sjc.microlink.io/DVJDQ3wUk9QXUWy7GY47WaPNLYmQv1QC1OhzSvfoR5PuTUyDse9a_P9m7MjzkevgatTeWz5empdb512Rvjhi6w.png">(view full size)</a> |<a href="https://v3-oodkjhcf5.hackclub.dev/bank">Screenshot of /bank</a><br /><sup><a href="https://images.weserv.nl?url=https://sjc.microlink.io/LcVsF0hES5XshP2fU8ISW-1Y-kzKNIX4CukFWmXCW0nTZfJldJKhBvyZHuLiW3eH9wahJ-XKCNCGjFPZq1ZCpg.png">(view full size)</a> |



| [**/bank/success**](https://v3-oodkjhcf5.hackclub.dev/bank/success) |
|:-:|
|<a href="https://v3-oodkjhcf5.hackclub.dev/bank/success">Screenshot of /bank/success</a><br /><sup><a href="https://images.weserv.nl?url=https://sjc.microlink.io/37evIR6YvHJmRczxbkW_m5lbco_XlZR0ixjdmiOFHClShcaygWBye7dA6sZKTDz8ZSpZhwSgz_MNiXbSwp-URw.png">(view full size)</a> |



And 1 other route:
- [**/api/bank-apply**](https://v3-oodkjhcf5.hackclub.dev/api/bank-apply)



Commit ec5755670a962e0084be4d4f8f337be1e6918aef (https://v3-oodkjhcf5.hackclub.dev).

**Review by sampoder — CHANGES_REQUESTED** [review]
Hiya Ella!

Any reason the smaller form was removed from `/bank`? I think it made it a lot more obvious for people on how to apply. When I was scrolling through I actually missed the button at first.

Some other thoughts:

The birthday form seems a bit oversized:

Screenshot 2022-01-30 at 9 15 53 AM

Mailing address should probably be a subheading:

Screenshot 2022-01-30 at 9 16 16 AM


Thanks!

Sam

**Comment by exu3** [comment]
Thanks for the review Sam!

> Any reason the smaller form was removed from /bank? I think it made it a lot more obvious for people on how to apply. When I was scrolling through I actually missed the button at first.

I prefer the form there as well! I've added it back.

> The birthday form seems a bit oversized:

Fixed: 
Screen Shot 2022-01-29 at 7 37 58 PM

> Mailing address should probably be a subheading:

Screen Shot 2022-01-29 at 7 38 46 PM

---

#### Quick question:

In development, the [confirmation page](https://v3-4m6ex9c69.hackclub.dev/bank/apply/success/) loads upon submission, but in staging, I get a blank page when I submit + I have to refresh to get the page content to show up. Any idea what might be causing this?

**Comment by sampoder** [comment]
@eilla1 I just pushed a fix for that re: your question!

**Review by sampoder — APPROVED** [review]

**Comment by exu3** [comment]
Hey @maxwofford, this was already merged, but just wanted to check if you had any thoughts on this change?

**Comment by garyhtou** [comment]
Should we have hack.af redirect to the new form?

**Comment by exu3** [comment]
Yeah, after hackclub/bank#2278 is merged though because the field names are different than the Airtable form (`?prefill_Field%20Name=something` vs `?fieldName=something`)

**Pull request merged**
