### PR TITLE
HCB Apply: Add message about Slack being for teenagers only

### PR DESCRIPTION
**Pull request by Chay2203**
This issue solves part of #1099 

**Description**
I have made a change that was requested in the above issue by @dwahbe, please review it accordingly

### CODE REVIEW

**Comment by Chay2203** [comment]
@garyhtou @dwahbe I have updated the form and made the requested changes, please have a look at it :)

**Comment by garyhtou** [comment]
@dwahbe would you mind handling the review for this PR since you requested this?
ticket: https://github.com/hackclub/site/issues/1099#issuecomment-1982065351

cc @lachlanjc since you're been working on this page recently

**Comment by dwahbe** [comment]
This looks great on my side! Thank you!!

**Review by garyhtou — APPROVED** [review]
Thanks!
image

**Pull request merged**
