### PR TITLE
Add hackclub.com/start to redirects

### PR DESCRIPTION
**Pull request by exu3**
https://hackclub.slack.com/archives/C0C78SG9L/p1644388394268679
Screen Shot 2022-02-08 at 22 35 39

### CODE REVIEW

**Comment by cjdenio** [comment]
Hmm, I think this should be a redirect instead.

**Comment by sampoder** [comment]
Personally, I think we should keep it going to `/` so people have info about the stuff

**Comment by exu3** [comment]
Ah that's fair; I don't really have a strong opinion here, so feel free to revert this PR

**Comment by sampoder** [comment]
@cjdenio thoughts?

**Comment by cjdenio** [comment]
Hmm, I think keeping it at `/` sounds reasonable

**Pull request merged**
