### PR TITLE
Design improvements to Fiscal Sponsorship pages

### PR DESCRIPTION
**Pull request by lachlanjc**

### CODE REVIEW

**Comment by lachlanjc** [comment]
#### 📝 Changed routes:


| [**/fiscal-sponsorship/about**](https://site-lj5knw9cw.hackclub.dev/fiscal-sponsorship/about) | [**/fiscal-sponsorship/first**](https://site-lj5knw9cw.hackclub.dev/fiscal-sponsorship/first) |
|:-:|:-:|
|<a href="https://site-lj5knw9cw.hackclub.dev/fiscal-sponsorship/about">Screenshot of /fiscal-sponsorship/about</a><br /><sup><a href="https://images.weserv.nl?url=https://sjc.microlink.io/02hhTvR_j9zcJnjC5E_YKTkOrspZK7FnpC0SjtjsZjd3PBnt-t9HDL_3Wk7Gt_U0J_uD-pAhIOeCmgkr8XWgYw.png">(view full size)</a> |<a href="https://site-lj5knw9cw.hackclub.dev/fiscal-sponsorship/first">Screenshot of /fiscal-sponsorship/first</a><br /><sup><a href="https://images.weserv.nl?url=https://sjc.microlink.io/WLccESKpnZJjlZvXXFPo57A9jDAe7BW7SdNa_9zm1TljN7vbPlsvjlCW-x8QZynHQ1JeFMcuocElM6wC3qgeWQ.png">(view full size)</a> |



| [**/fiscal-sponsorship**](https://site-lj5knw9cw.hackclub.dev/fiscal-sponsorship) |
|:-:|
|<a href="https://site-lj5knw9cw.hackclub.dev/fiscal-sponsorship">Screenshot of /fiscal-sponsorship</a><br /><sup><a href="https://images.weserv.nl?url=https://sjc.microlink.io/iIsBi3SYIZ55CapMOrY7poiRNYL4RTiocigjlu1Sk5sSKb5unNwqZWfm6HpWWiHLgV4uZn9M3quX70LFcvLtJw.png">(view full size)</a> |







Commit ecc667df5d1367a3f0051fb8e0b59b0e82d8effc (https://site-lj5knw9cw.hackclub.dev).

**Comment by zachlatta** [comment]
LGTM to me. Please add appropriate redirect for `/fiscal-sponsorship/fiscal-sponsorship` -> `/fiscal-sponsorship/about`. Please make it 302 redirect (not cached).

Confirming there are no changes to `/apply`?

**Review by zachlatta — APPROVED** [review]

**Comment by lachlanjc** [comment]
That redirect should already be live! No changes to application.

**Comment by zachlatta** [comment]
I get a 404 when I go to current preview and try to go to
/fiscal-sponsorship/fiscal-sponsorship

--
Zach Latta
https://zachlatta.com <http://zachlatta.com>
@zachlatta <https://twitter.com/zachlatta> / fb
<https://www.facebook.com/crynix> / github <https://github.com/zachlatta>

**Comment by zachlatta** [comment]
I am running into meetings and thumbs up to merge when you’re ready.

**Comment by lachlanjc** [comment]
That URL was never live, so we don’t need to worry about a redirect from it. The page was previously at `/hcb/fiscal-sponsorship`, which now redirects to `/fiscal-sponsorship/about`

**Pull request merged**
