### PR TITLE
Added Board of Directors

### PR DESCRIPTION
**Pull request by abbyfischler**
@christinaasquith changed footer from "donate" to Donate / Board of Directors

### CODE REVIEW

**Review by sampoder — CHANGES_REQUESTED** [review]
This feels too long in comparison to the other items in the footer:

Screenshot 2023-02-20 at 11 04 46 AM

The slash also looks outs of place.

Thoughts on just going with "Philanthropy"?

**Comment by christinaasquith** [comment]
I'd like our site to say Board as any major donor that comes to the site looks for that. 

 I like: Philanthropy / Board. 

But it is also important that visitors easily see how to donate as we do get lots of small donations. Any thoughts on where we could move DONATE?

**Comment by sampoder** [comment]
x-posting from Slack:

I think we’re trying to say too much in the footer at the moment and I worry if people are looking for the board, /philanthropy/ may not be the ideal place to send them. what if we featured the board prominently on https://hackclub.com/team and renamed it to “Our Team & Board” / “Team & Board” / “Our Board & Team” / “The Team & Board” in the footer?

**Comment by sampoder** [comment]
Closing - superseded by #713

**Pull request closed without merging**
