### PR TITLE
hackclub.com/bank/first

### PR DESCRIPTION
**Pull request by exu3**
This PR adds a page at hackclub.com/bank/first to promote Hack Club Bank as a tool for FIRST teams.

### CODE REVIEW

**Comment by lachlanjc** [comment]
#### 📝 Changed routes:


| [**/bank/first**](https://site-ehvkt4rxp.hackclub.dev/bank/first) |
|:-:|
|<a href="https://site-ehvkt4rxp.hackclub.dev/bank/first">Screenshot of /bank/first</a><br /><sup><a href="https://images.weserv.nl?url=https://sjc.microlink.io/oJu9jrlZYzprgnLdLf4qZCMCAtABcWd6aATZDdMcGibtWv3htXPPkkphoFfE_8WMAS-mXwwgzmbYE5M9JAIYpw.png">(view full size)</a> |



And 2 other routes:
- [**/api/bank/apply**](https://site-ehvkt4rxp.hackclub.dev/api/bank/apply)
- [**/api/bank/demo**](https://site-ehvkt4rxp.hackclub.dev/api/bank/demo)



Commit 77613e9e01e1e3e65e25d09eb3520c67d2f2fd47 (https://site-ehvkt4rxp.hackclub.dev).

**Comment by sampoder** [comment]
I think this page is super cool! What if the header had an image of a robotics team / competition? Maybe one of Caleb's old ones

**Comment by exu3** [comment]
That would be great if Caleb has one; I was asking the FIRST teams on Bank for such an image, to no avail.

**Comment by sampoder** [comment]
Worst case, we could ask First

**Comment by exu3** [comment]
Reviewed irl!

**Pull request merged**
