### PR TITLE
Super non-critical changes for secret-santa refresh

### PR DESCRIPTION
**Pull request by maxwofford**
Love the updates you made! Feeling cute, might commit later

### CODE REVIEW

**Comment by lachlanjc** [comment]
#### 📝 Changed routes:


| [**/santa**](https://v3-f8rmrgcox.hackclub.dev/santa) |
|:-:|
|<a href="https://v3-f8rmrgcox.hackclub.dev/santa">Screenshot of /santa</a><br /><sup><a href="https://images.weserv.nl?url=https://sjc.microlink.io/irHGjsx07SI6X3ky9POykMyiZv8ecIYNtVo10FpJxt7Wkf2s5_KuxjMdfcICXhlzpj4fpvHvwC04Ioj_M5K-ug.png">(view full size)</a> |







Commit 358636b98d795cc7156e5484345c8f0fa9cf032e (https://v3-f8rmrgcox.hackclub.dev).

**Review by exu3 — APPROVED** [review]
It looks awesome, thanks! I love the transition.

I also added a form at the bottom similar to the one on the Bank page. Thoughts on that? Feel free to revert if it doesn't fit.

**Comment by maxwofford** [comment]
@eilla1 that's great! I saw the numbers were off (it didn't increment when I added my "likes"). Go ahead and merge when you think it's ready!

**Comment by sampoder** [comment]
quick thing I spotted



ill send a pr over in a couple of minutes

**Comment by exu3** [comment]
From your screenshot it looks like you were using an older preview link / not the most recent one? Anyways, thanks for the PR!

**Pull request merged**
