### PR TITLE
Edit copy on annoucement banner

### PR DESCRIPTION
**Pull request by exu3**
Hmmm I'm not sure. THoughts?

Screen Shot 2022-08-17 at 2 24 29 PM

### CODE REVIEW

**Comment by lachlanjc** [comment]
#### 📝 Changed routes:


| [**/**](https://site-6xkfdyqaq.hackclub.dev/) |
|:-:|
|<a href="https://site-6xkfdyqaq.hackclub.dev/">Screenshot of /</a><br /><sup><a href="https://images.weserv.nl?url=https://sjc.microlink.io/-ZvpPRaQ5dwcqYpg6IE0oxIKhf7DALEYrOquhl5UQbyrCV8xO9YBjj2zWJOiT7FJ_MVqHmgoEsHRWa_-FQEbzQ.png">(view full size)</a> |







Commit 1e2ab5cf8e5cbc9476f70987c3103fb16a4dd54f (https://site-6xkfdyqaq.hackclub.dev).

**Comment by bellesea** [comment]
this sounds cool! i'm not super sure about `with support from Hack Club and FIRST` because it makes me think that beyond the $500, there's some further support for your hackathon... not sure if that makes sense?

**Comment by sampoder** [comment]
with Bank + hackathons.hackclub.com there kinda is

**Review by sampoder — APPROVED** [review]
I like it!

**Pull request merged**
