### PR TITLE
Added a jobs page

### PR DESCRIPTION
**Pull request by abbyfischler**
This is not complete at all. Just a rough draft. Thanks @maxwofford for your help.

### CODE REVIEW

**Comment by lachlanjc** [comment]
#### 📝 Changed routes:


| [**/jobs**](https://v3-16y4o5a1c.hackclub.dev/jobs) | [**/stickers**](https://v3-16y4o5a1c.hackclub.dev/stickers) |
|:-:|:-:|
|<a href="https://v3-16y4o5a1c.hackclub.dev/jobs">Screenshot of /jobs</a><br /><sup><a href="https://images.weserv.nl?url=https://sjc.microlink.io/qAnF6fUhIgaCSdf2Gg-axI3pjwVvSQfX8YtdkE-nAgq9Ls0tWbUhCgImh4d2OXmURvsWeBEP5IAfdqtnVLmwHQ.png">(view full size)</a> |<a href="https://v3-16y4o5a1c.hackclub.dev/stickers">Screenshot of /stickers</a><br /><sup><a href="https://images.weserv.nl?url=https://sjc.microlink.io/yVUvsEhmiq3XQZiY4fZast0Ot2U_MYGi4T23gT3_Ma5DWEkAAYtk71oxm-yFM4PMoqVrZ_GX2tOI-hrBw5GNBw.png">(view full size)</a> |







Commit 646f941c635c21aee9795043f9cdd7d294a543f2 (https://v3-16y4o5a1c.hackclub.dev).

**Review by sampoder — CHANGES_REQUESTED** [review]
We'll need to comment this out in `next.config.js`:

```
{
        source: '/jobs/',
        destination: 'https://jobs.hackclub.com',
        permanent: false
}
```

**Review by maxwofford — APPROVED** [review]
I just put a couple changes in https://github.com/abbyfischler/v3/pull/2. Once you merge that, I'm cool with this getting merged in. I think there's a little more love we can give it in the future, but this is a great addition to the site with our deadline of tonight.

**Comment by sampoder** [comment]
Could we make it fit in a bit more with the wider design of the site? I can give it a shot tonight but I feel that it doesn't really fit in. Also, we're pretty conservative with the items we place in the navigation bar, I feel like this would fit in a bit better in the footer. Just my two cents

**Comment by sampoder** [comment]
I'm rebasing this into the repo to make some updates (Max asked)

**Comment by abbyfischler** [comment]
@sampoder This looks amazing, thanks for your help!

**Pull request merged**
