### PR TITLE
change slack copy for over 18+

### PR DESCRIPTION
**Pull request by radioblahaj**
cc @karamassie @maxwofford

### CODE REVIEW

**Comment by maxwofford** [comment]
I'm cool with merging this, but you don't need to capitalize "minor"

**Comment by radioblahaj** [comment]
Let me fix that. Sorry about that!

**Comment by sampoder** [comment]
Is minors the best word to use? Feels like what my school uses in all their serious policies...

**Comment by karamassie** [comment]
yes, and because of that is why i'm suggesting it @sampoder . i'm getting tons of adults asking to join still and listing their credentials and reason (ie the message is somehow 'we're vetting people based on something else besides age here'.  i have to email all of them that the reason is it's a community of MINORS, and when they respond theyre like "ohhhhhh".

**Comment by radioblahaj** [comment]
just bumping this :)

**Review by YodaLightsabr — APPROVED** [review]
Looks good!

**Pull request merged**
