### PR TITLE
removed sprig consoleCount for Shawn

### PR DESCRIPTION
**Pull request by aramshiva**
Screenshot 2023-11-30 at 6 03 49 PM
@Sheepy3

### CODE REVIEW

**Comment by aramshiva** [comment]
oh also it removes FIRST in metadata as a partner of the Hackathon grant as they are no longer.

**Comment by lachlanjc** [comment]
#### 📝 Changed routes:


| [**/hackathons/grant**](https://site-3tdb9kpmn.hackclub.dev/hackathons/grant) | [**/**](https://site-3tdb9kpmn.hackclub.dev/) |
|:-:|:-:|
|<a href="https://site-3tdb9kpmn.hackclub.dev/hackathons/grant">Screenshot of /hackathons/grant</a><br /><sup><a href="https://images.weserv.nl?url=https://sjc.microlink.io/d1peuNOpl4t27IBDW9D-7Rw0daKdduzm1Rn4_B9C4Y2S4aIN1FWrFxMPujA1bpjsiDHRNBO8YVk_teJTjdHUvw.png">(view full size)</a> |<a href="https://site-3tdb9kpmn.hackclub.dev/">Screenshot of /</a><br /><sup><a href="https://images.weserv.nl?url=https://sjc.microlink.io/uqdtQGb-kC7V7m0u4tDlKQE1ocKpKrWR46feBAabUAVo2-WdTTPVooarVdwtArTy4VEwshR3vHMg-tuveX6jdQ.png">(view full size)</a> |





1 deleted route:
- **/api/sprig-console**

Commit 0dc35c9fb3fa26c29be7b3f8d9b60545d4254122 (https://site-3tdb9kpmn.hackclub.dev).

**Comment by aramshiva** [comment]
deleted this route as only used by the X consoles left card

**Comment by aramshiva** [comment]
Will open new one soon

**Comment by aramshiva** [comment]
moved to #1014

**Pull request closed without merging**
