### PR TITLE
Pitch bank better

### PR DESCRIPTION
**Pull request by quackduck**
Pitch Bank better by relating it to the viewer and removing “for hackers”, reducing an awkward interruption, which the rest of the page makes clear anyways.

### CODE REVIEW

**Comment by quackduck** [comment]
This PR brought to you completely from mobile :eggsdee:

**Review by sampoder — CHANGES_REQUESTED** [review]
I personally prefer using the "hackers" label, @MelSmith104 thoughts?

**Comment by eilla1** [comment]
Appreciate the PR Ishan! However, I disagree with this copy change because "a bank for student hackers" is basically a part of Bank's brand and has been used since the [beginning](https://medium.com/hackclub/hack-club-bank-is-now-live-for-everyone-including-you-884f7f54836f)

**Comment by quackduck** [comment]
Makes sense! 👍

**Comment by MelSmith104** [comment]
Same as what ella and sam said - a bank for hackers has always been what HCB was created for and its our origin story. i like that we're growing but it makes sense to keep that up as a nod to where we started

**Pull request closed without merging**
