### PR TITLE
feat: modified old slack page

### PR DESCRIPTION
**Pull request by tobySolutions**
slack

https://github.com/hackclub/site/assets/96334363/701af09f-7cbd-4209-9aed-9bea6552a6ab

### CODE REVIEW

**Comment by lachlanjc** [comment]
#### 📝 Changed routes:


| [**/slack**](https://site-ke96svbzo.hackclub.dev/slack) |
|:-:|
|<a href="https://site-ke96svbzo.hackclub.dev/slack">Screenshot of /slack</a><br /><sup><a href="https://images.weserv.nl?url=https://sjc.microlink.io/7DSjuI7GkBkqooasVf5YAePo5Ujo7jtA6lOMPkbtchdBd0UvD6CNSQYBpM7Das9oe8zyC0kjkqNGyOapIPuUSA.png">(view full size)</a> |







Commit 222915eeca21ff05023a849d84f872a8bbc1c1b9 (https://site-ke96svbzo.hackclub.dev).

**Comment by bellesea** [comment]
OMG cool design!!! btw it's now 25k+ total members :) also, i kinda liked the slightly mosaic design from the previous verison... anyway we could bring that back? love how clean it feels though! also, would you want to give the responsiveness another pass?

**Review by sampoder — COMMENTED** [review]
hey @tobySolutions! curious, what's the rational behind removing the video? personally, I really liked it.

**Comment by tobySolutions** [comment]
> OMG cool design!!! btw it's now 25k+ total members :) also, i kinda liked the slightly mosaic design from the previous verison... anyway we could bring that back? love how clean it feels though! also, would you want to give the responsiveness another pass?


Hey @bellesea, thank you very much for the awesome review. 

I made a redesign of the existing page that's the reason behind the 25k+ not being on there on the site. I can just update that though.


Could you show me the issues you're getting with the responsiveness?? 👀👀. It's totally fine on all the devices I tested with.

**Comment by tobySolutions** [comment]
> hey @tobySolutions! curious, what's the rational behind removing the video? personally, I really liked it. 

Hey @sampoder thank you for bringing this up. The reason I took out the video came from analyses as to how I can improve the page by professional UX engineers. 

One said and I quote: "The experience isn't really good, it distracts the user from the main purpose of the page as it is unnecessary". 

I hope you understand this though.

**Comment by tobySolutions** [comment]
> #### 📝 Changed routes:
> 
> 
> | [**/slack**](https://site-p33i0nrvv.hackclub.dev/slack) |
> |:-:|
> |<a href="https://site-p33i0nrvv.hackclub.dev/slack">Screenshot of /slack</a><br /><sup><a href="https://images.weserv.nl?url=https://sjc.microlink.io/7voyG8zDkHFmd-YFoyISy__9WX5rXrohMA1Lv_DZ2wkz-cwIbooDLTUU8Xa_RLnmaMSG3kN9qP8wN1WlD-bbmw.png">(view full size)</a> |
> 
> 
> 
> 
> 
> 
> 
> Commit 41e5e33c77eb46a0333460ebffc69b71125301e4 (https://site-p33i0nrvv.hackclub.dev).

Thank you very much for this. What do you mean by changed routes?

**Comment by sampoder** [comment]
> > hey @tobySolutions! curious, what's the rational behind removing the video? personally, I really liked it.
> 
> Hey @sampoder thank you for bringing this up. The reason I took out the video came from analyses as to how I can improve the page by professional UX engineers.
> 
> One said and I quote: "The experience isn't really good, it distracts the user from the main purpose of the page as it is unnecessary".
> 
> I hope you understand this though.

I'm not sure I quite understand, are they on GitHub?

**Comment by tobySolutions** [comment]
> > > hey @tobySolutions! curious, what's the rational behind removing the video? personally, I really liked it.
> > 
> > Hey @sampoder thank you for bringing this up. The reason I took out the video came from analyses as to how I can improve the page by professional UX engineers.
> > 
> > One said and I quote: "The experience isn't really good, it distracts the user from the main purpose of the page as it is unnecessary".
> > 
> > I hope you understand this though.
> 
> I'm not sure I quite understand, are they on GitHub?

My consultants?

**Comment by tobySolutions** [comment]
By the way, everyone I've heard and seen some of the issues you pointed out, I'll make another PR to get it fixed soon. 

They're just minor styling issues.

**Comment by tobySolutions** [comment]
Let me know what you think @sampoder. Thank you. I can share my Figma design so you can have a look.

**Comment by tobySolutions** [comment]
Hey, @bellesea, @lachlanjc, @sampoder, @motdotla (sorry for tagging all of you). I'd like to hear your new reviews on what I've implemented now; I made the changes requested by you Belle.

However, the User Experience with the video in the background in the hero section of the existing site isn't good and I can expand on this further if you'd like me to.

Although I need some help sorting out the trending channels as I'm not on the Slack channel and further updates on updating the trending channels might be one of the ways people actively contribute to this page. Thank you all.

**Comment by bellesea** [comment]
hey @tobySolutions thank you so much for making this PR! the site looks awesome but in my opinion, our existing site better encapsulate's hack club's brand and soul... yes the video might be a little distracting but it shows you what real conversations in the slack look like, and a big call out of how many members is more visible than a small badge in the corner... for trending channels, idk if that's more efficient than "live from our slack... (screenshot below)" or smth like that? it would be great though to add more channels to the whitelist so it shows typing more often :)

Screenshot 2023-06-28 at 12 27 50 PM

i'd love to know what you think!

**Comment by tobySolutions** [comment]
> hey @tobySolutions thank you so much for making this PR! the site looks awesome but in my opinion, our existing site better encapsulate's hack club's brand and soul... yes the video might be a little distracting but it shows you what real conversations in the slack look like, and a big call out of how many members is more visible than a small badge in the corner... for trending channels, idk if that's more efficient than "live from our slack... (screenshot below)" or smth like that? it would be great though to add more channels to the whitelist so it shows typing more often :)
> 
> Screenshot 2023-06-28 at 12 27 50 PM
> 
> i'd love to know what you think!



Okay. So about the video at the background being removed was needed it was too enlarged and I really didn't think of the need to be there as it was a little distracting. The call out of how many members can be centralized just below the hack club text.


Although the reason as to which it was at the right was for people to see immediately but I guess it's too small. Apologies on that. Then moving to the live on our slack was a little bit confusing with other tags  beside hence the remodel for you to track what's going on live and view all forms of channels separately. In that way it keeps that section from looking too busy. That was my thought on the remodelling.


I was gunning for Simplicity. 😁😁😁

@bellesea.

**Comment by Tiger-The-Cat** [comment]
Thanks for submitting this, @tobySolutions! I think the UI and text placement is a great improvement, but I also agree that the background shouldn't be blank. 

I also find the video a little distracting, maybe replacing the video with a gallery of still images would be a good compromise?

If that doesn't work out, we could at least keep the gradient:
image

**Comment by zachlatta** [comment]
Hey, I'm closing this PR as I don't think it is currently a sufficiently large enough improvement on the current design given the other issues it introduces re: above.

**Pull request closed without merging**
