### PR TITLE
Add Jobs Page (#2)

### PR DESCRIPTION
**Pull request by sampoder**
This builds on Abby's previous PR but is done inside of the `v3` repo to help centralise things

### CODE REVIEW

**Comment by lachlanjc** [comment]
#### 📝 Changed routes:


| [**…communications-manager**](https://v3-5g78581nl.hackclub.dev/jobs/communications-manager) | [**/jobs/education-engineer**](https://v3-5g78581nl.hackclub.dev/jobs/education-engineer) |
|:-:|:-:|
|<a href="https://v3-5g78581nl.hackclub.dev/jobs/communications-manager">Screenshot of /jobs/communications-manager</a><br /><sup><a href="https://images.weserv.nl?url=https://sjc.microlink.io/DKyM-hcp8_uwBv-WRRE1Uikt9kB8UzRy7O9ey3aLrxFB4wqh0jzOTV0N3La2cr5ZVBCpAIjG3RdeTl02gfztTQ.png">(view full size)</a> |<a href="https://v3-5g78581nl.hackclub.dev/jobs/education-engineer">Screenshot of /jobs/education-engineer</a><br /><sup><a href="https://images.weserv.nl?url=https://sjc.microlink.io/R-0Fam_Udjgur3H0v2SEGAhxfeHE35nk3h-N9EuVrJ3ejV3e6Xqo0bsLVmbcu1kB5B7z6kEtSxB3B5oyas38dg.png">(view full size)</a> |



| [**/jobs**](https://v3-5g78581nl.hackclub.dev/jobs) | [**…/philanthropy-position**](https://v3-5g78581nl.hackclub.dev/jobs/philanthropy-position) |
|:-:|:-:|
|<a href="https://v3-5g78581nl.hackclub.dev/jobs">Screenshot of /jobs</a><br /><sup><a href="https://images.weserv.nl?url=https://sjc.microlink.io/Zs7QieI-SNOhmsU9V6xJXJdr3iMCSCgi33ka6cYDUsHbaNVAZ3le02lUH2hUagPH6A1Ky1K8vcDRthPS7MWseg.png">(view full size)</a> |<a href="https://v3-5g78581nl.hackclub.dev/jobs/philanthropy-position">Screenshot of /jobs/philanthropy-position</a><br /><sup><a href="https://images.weserv.nl?url=https://sjc.microlink.io/QkYvrKQ7Oy7ZfSLnMXwZQgV8YJYWHZnB0NGLgVBtVVovLFYRp6XAj_BbjZACjd15jV5aQicnPITvx7DJ5CW5fQ.png">(view full size)</a> |



| [**/stickers**](https://v3-5g78581nl.hackclub.dev/stickers) |
|:-:|
|<a href="https://v3-5g78581nl.hackclub.dev/stickers">Screenshot of /stickers</a><br /><sup><a href="https://images.weserv.nl?url=https://sjc.microlink.io/fx6fGxtrjBv7ibIHZLdBmTN7eHq8LoTemGFHgZwmaRv1OK4Pad0F26EKQYhsIH7uGOiMadbVRs5PJwyGKJbkTA.png">(view full size)</a> |







Commit 2f5ec96a02ff71ecc844f858a99f205ea094fa3f (https://v3-5g78581nl.hackclub.dev).

**Comment by sampoder** [comment]
Mobile still needs work tho

**Review by maxwofford — APPROVED** [review]
This looks awesome! Thanks for sprinkling that magic dust on the page, starting to look real shiny. We can def work on the mobile view, but this is a pretty good-looking page on my laptop's screen. Maybe we can merge for now & keep working on the mobile view?

**Comment by sampoder** [comment]
gadzooks! lets do it!

**Pull request merged**
