### PR TITLE
Fixes local development environment

### LINKED ISSUE #720: Local dev setup is broken
Following the local dev setup instructions fails with the following error when loading http://localhost:3000/ :

Screenshot 2023-02-23 at 10 47 49 AM

This error was reproduced locally by @maxwofford as well.

### PR DESCRIPTION
**Pull request by grymmy**
Prior to this change the front page wouldn't load when running locally following the README directions.

See [related issue](https://github.com/hackclub/site/issues/720).

### CODE REVIEW

**Review by exu3 — APPROVED** [review]
This works great, thanks for fixing! 

Only thing I might suggest is formatting your code with Prettier `npx prettier --write .` (which uses the prettier configuration defined in prettier.config.js). However, it seems like a lot of the files in this repo are not formatted, so running that on your branch in its current state would change a lot of other files. Unrelated to this PR, but perhaps there should be a note in the README to run `npx prettier --write .` when contributing code.

**Review by bellesea — APPROVED** [review]
ahhh thank you sm!!

**Comment by grymmy** [comment]
@exu3 Thanks for the heads up, I will check prettier, and keep that in mind in the future!  Perhaps once we go through and format the entirety of the code we can add some lint checks to fail merges automagically when things aren't formatted?  There's also the option to automagically run the desired formatting on commit using [git hooks](https://git-scm.com/book/en/v2/Customizing-Git-Git-Hooks).

[edit] related - could make sense to look at this warning that shows up in github:

Screenshot 2023-02-23 at 8 43 07 PM

**Comment by sampoder** [comment]
thanks for this!

**Pull request merged**
