### PR TITLE
added extra info to "free domains"

### PR DESCRIPTION
**Pull request by P1xelC0da**

### CODE REVIEW

**Review by bellesea — APPROVED** [review]
this looks good to me, cc @hackclub/bank-engineering or @hackclub/bank-ops for review as well! :)

**Comment by sampoder** [comment]
personally, this feels a bit verbose to me. I think most domains fall under $20 anyways

**Comment by P1xelC0da** [comment]
It depends on the domain name, really. But just saying that we’ll pay 
for a year, is too vague.

---
Damian Freeman

**Comment by sampoder** [comment]
hey! looks like this PR has gone inactive, I'm going to close it

**Comment by P1xelC0da** [comment]
What am I supposed to do other than let it sit if no one from HQ seems 
to want to merge it? Of course it's going to be inactive.

**Pull request merged**
