### PR TITLE
Implement A Waitlist

### LINKED ISSUE #352: Slack signup disable feature
We've had to occasionally lock down our slack signup form and API when someone tweets about us (most recently [Vitalik](https://twitter.com/VitalikButerin/status/1489409521806020611)).

In the past these have been kinda last-second and could be so much better (see https://github.com/hackclub/site/pull/338).
Screen Shot 2022-02-07 at 09 58 39

It'd be cool to have a nice looking waitlist form that can be enabled that explains our signups are temporarily locked down but a user can fill out the form to join the waitlist, and we'll review applications in a couple days.

### PR DESCRIPTION
**Pull request by sampoder**

### CODE REVIEW

**Comment by lachlanjc** [comment]
#### 📝 Changed routes:



- [**/api/join**](https://v3-jqpx0r4mv.hackclub.dev/api/join)



Commit 6ca6b3bdc2abee107f1cd57e2ebf3993ceea7769 (https://v3-jqpx0r4mv.hackclub.dev).

**Comment by sampoder** [comment]
If the `NEXT_PUBLIC_OPEN` env var is set to `false`, it will not invite them to Slack only create a Airtable record on Slack Join Requests. To then release them from the waitlist and invite them to the Slack the `Airtable Invite Needed` checkbox must be checked on Airtable, then an automation will send them an invite.

Waitlist off: https://v3-jqpx0r4mv.hackclub.dev/
Waitlist on: https://v3-gsxy2jd93.hackclub.dev/

**Comment by maxwofford** [comment]
This is great! Could we have a little message that says why we're temporarily creating the waitlist? Also, should we have an email confirmation for the waitlist (letting people know we got their submission)

**Comment by maxwofford** [comment]
cc @zfogg

**Comment by zfogg** [comment]
awesome!! ill review in like one hour

**Comment by sampoder** [comment]
whatcha think Zach?

**Pull request merged**
