### PR TITLE
Change @maxwofford's team role to Master Memer

### PR DESCRIPTION
**Pull request by kognise**

### CODE REVIEW

**Comment by lachlanjc** [comment]
#### 📝 Changed routes:


| [**/team**](https://site-62lilhvvx.hackclub.dev/team) |
|:-:|
|<a href="https://site-62lilhvvx.hackclub.dev/team">Screenshot of /team</a><br /><sup><a href="https://images.weserv.nl?url=https://sjc.microlink.io/mLeNaOFNEzux7DwPiBR-Ce7X-qgR4OhEb5b4dkBiEieLiAyrd1RjgbUErU6JZRFXQskAHgl_wtqY9IovfvPE1A.png">(view full size)</a> |







Commit c5bdadcbe7206e55fa96914a0d60b20d2b0824e8 (https://site-62lilhvvx.hackclub.dev).

**Review by reesericci — APPROVED** [review]
Fully approve of this PR

**Review by malted — APPROVED** [review]
+1

**Review by maxwofford — CHANGES_REQUESTED** [review]
EDIT: sound on

https://user-images.githubusercontent.com/5891442/230546476-85af8a1a-c538-462e-b093-adcaedb7c3c0.mp4

**Comment by maxwofford** [comment]
Closing for reasons listed above

**Comment by reesericci** [comment]
you can't argue with that

**Pull request closed without merging**
