### PR TITLE
HC & FIRST Logos

### PR DESCRIPTION
**Pull request by bellesea**
Would appreciate wording suggestions, thank you sm!

### CODE REVIEW

**Review by maxwofford — COMMENTED** [review]
Love the links! What about "Once you've received your grant, you can (optionally) include Hack Club and FIRST's logos on your site"

**Comment by bellesea** [comment]
> Love the links! What about "Once you've received your grant, you can (optionally) include Hack Club and FIRST's logos on your site"

This phrasing is definitely tighter but i feel like it places us in favour of our logo being placed... would that sentiment be correct?

**Comment by exu3** [comment]
Suggestion:

If you'd like to list us on your site (optional), you can use the logos found on the respective brand guides for [Hack Club](https://hackclub.com/brand) and [_FIRST_](https://uwu.boats/important).

But I also wonder if this something that would fit better somewhere in the grant application flow itself?

**Comment by bellesea** [comment]
> Suggestion:
> 
> If you'd like to list us on your site (optional), you can use the logos found on the respective brand guides for [Hack Club](https://hackclub.com/brand) and [_FIRST_](https://uwu.boats/important).
> 
> But I also wonder if this something that would fit better somewhere in the grant application flow itself?

I like this phrasing! Hmm, i thought about this but might be good to have it somewhere for reference? Having it in the flow itself could be cool too tho :)

**Review by sampoder — APPROVED** [review]
Looks good to me! Merging to move this along. Feel free to revert.

**Comment by bellesea** [comment]
> Looks good to me! Merging to move this along. Feel free to revert.

Thank you!

**Pull request merged**
