### PR TITLE
Create the summer arcade

### PR DESCRIPTION
**Pull request by maxwofford**

### CODE REVIEW

**Comment by lachlanjc** [comment]
#### 📝 Changed routes:


| [**…/\[userAirtableID\]/shop**](https://site-8vmn9vbkt.hackclub.dev/arcade/[userAirtableID]/shop) | [**/arcade**](https://site-8vmn9vbkt.hackclub.dev/arcade) |
|:-:|:-:|
|<a href="https://site-8vmn9vbkt.hackclub.dev/arcade/[userAirtableID]/shop">Screenshot of /arcade/[userAirtableID]/shop</a><br /><sup><a href="https://images.weserv.nl?url=https://sjc.microlink.io/xyppcQh3mPDNuD0WCFnvw1GCRYQn3x4Bh8giEbpxma4Mf03Me5JRpHOm4qjKJaawBXhycMASmAMKNKOebo9_hw.png">(view full size)</a> |<a href="https://site-8vmn9vbkt.hackclub.dev/arcade">Screenshot of /arcade</a><br /><sup><a href="https://images.weserv.nl?url=https://sjc.microlink.io/EI83vAK38l-78MkB1amDlO-VyThZXs9SbPNvIukLI1aFs6b7M1N_kZUsXE78FbV1joq3XFN0F7WZ-hzwvmxZqw.png">(view full size)</a> |



| [**/**](https://site-8vmn9vbkt.hackclub.dev/) | [**/onboard/gallery**](https://site-8vmn9vbkt.hackclub.dev/onboard/gallery) |
|:-:|:-:|
|<a href="https://site-8vmn9vbkt.hackclub.dev/">Screenshot of /</a><br /><sup><a href="https://images.weserv.nl?url=https://sjc.microlink.io/nj3xobDqROa0ISKVx2P_43LvIf2-_oOd0stWDeowSZ8--0fTUlRagqr2itwqpCBlVvCV_6sNLsYjh1rbAq5YtA.png">(view full size)</a> |<a href="https://site-8vmn9vbkt.hackclub.dev/onboard/gallery">Screenshot of /onboard/gallery</a><br /><sup><a href="https://images.weserv.nl?url=https://sjc.microlink.io/2-gIMJX7ImvEsvDI1yKH64NXf02iF5sw7TPtj9AW4Slxl_vJya9Ilkp9zh2B3mwr3uKekyKZtHQOa0_gvO0nEA.png">(view full size)</a> |



| [**/onboard/gallery/page**](https://site-8vmn9vbkt.hackclub.dev/onboard/gallery/page) |
|:-:|
|<a href="https://site-8vmn9vbkt.hackclub.dev/onboard/gallery/page">Screenshot of /onboard/gallery/page</a><br /><sup><a href="https://images.weserv.nl?url=https://sjc.microlink.io/SDjxpmj2DVQzR72pWD5M4LPLuDtJqnTxVi-UH4Hi6Z6hY9-3synizUaA2VHezpDzZW030Ra4nA1pHp0eolhk6w.png">(view full size)</a> |



And 5 other routes:
- [**/api/arcade/\[userAirtableID\]**](https://site-8vmn9vbkt.hackclub.dev/api/arcade/[userAirtableID])
- [**/api/arcade/hack-hour/inventory**](https://site-8vmn9vbkt.hackclub.dev/api/arcade/hack-hour/inventory)
- [**/api/arcade/openai**](https://site-8vmn9vbkt.hackclub.dev/api/arcade/openai)
- [**/api/arcade/shop**](https://site-8vmn9vbkt.hackclub.dev/api/arcade/shop)
- [**/api/arcade/slack**](https://site-8vmn9vbkt.hackclub.dev/api/arcade/slack)

1 deleted route:
- **/onboard/gallery/[page]**

Commit 745cbd8c7cb87797f2b3b5afbe9af93b9db9db7f (https://site-8vmn9vbkt.hackclub.dev).

**Comment by transcental** [comment]
Site's looking great, a few issues I've noticed so far:
- MacBook image doesn't load
- Lots of logging `undefined` in the console
- Grammatically wrong, should say "will be"
image

- Stickers using brackets for `(3 random)` where nothing else has brackets is a little odd
- Should list some specs

**Comment by devramsean0** [comment]
Few Accessibility concerns:
- Images next to tickets + on the marquee don't seem to have alt tags
- Some items seem to be in the marquee but not further down the page (not sure if this is intended or not)  \

General tidbits:
- Wizard Orpheus's mention isn't a valid link (unsure if this is intended again)

Otherwise it looks great to my untrained eye :)

**Comment by devramsean0** [comment]
Also, these appeared in the console, not sure if this is a general issue, or just an arc on windows thing
image

**Comment by transcental** [comment]
Can confirm that happens on Edge on Mac

**Comment by DevSrijit** [comment]
Screenshot 2024-06-15 at 11 30 50 PM
I get this logged when I click on the arcade machine for ideas.

**Comment by DevSrijit** [comment]
[Suggestion] - Modify FAQ 2. which states "You need to be a high schooler (or younger) in the United States." to indicate that it is also open to international hack clubbers. 
image

**Comment by devramsean0** [comment]
Also, there's no mention of the start/end date

**Comment by polypixeldev** [comment]
image
small typo "GitHub accound"

**Comment by transcental** [comment]
The #arcade channel doesn't exist, or is private. Should this be #power-hour-support or #arcade-help?
Additionally, making Hack Club Slack a link is probably a good idea
image

Also, you have to be in the slack to participate so maybe that copy could be adjusted to something like "Alternatively, you can email arcade@hackclub.com" (and make it a `mailto:` link as well)

**Comment by taciturnaxolotl** [comment]
The arcade channel exists now it was renamed from #hack-hour

**Pull request merged**
