### PR TITLE
Closed Arcade Shop

### PR DESCRIPTION
**Pull request by Aryankpoor**
Only for personal shop links

### CODE REVIEW

**Comment by lachlanjc** [comment]
#### 📝 Changed routes:


| [**…/\[userAirtableID\]/shop**](https://site-l6eun8mgi.hackclub.dev/arcade/[userAirtableID]/shop) |
|:-:|
|<a href="https://site-l6eun8mgi.hackclub.dev/arcade/[userAirtableID]/shop">Screenshot of /arcade/[userAirtableID]/shop</a><br /><sup><a href="https://images.weserv.nl?url=https://sjc.microlink.io/-YVv5VaJJfEB6yv1TXwB3Q4r1mmdb3g_qhLJgkJ2gfGJA-8BFTINpqpMvtSV6IbEzdLO-GnZ_C5iMjsBc8H0MQ.png">(view full size)</a> |







Commit 99c07384f5b6e9d6a8db56d68c01c14bff2d26c0 (https://site-l6eun8mgi.hackclub.dev).

**Review by maxwofford — CHANGES_REQUESTED** [review]
It looks like this removes the shop! I'd like something that just prevents people from buying

**Comment by Aryankpoor** [comment]
We already have done that! The form is closed now. If a person tries to buy anything, it asks them for a password to open the form ! Ian has already shared the password with us

**Comment by Aryankpoor** [comment]
Although I don't understand why we are still keeping the shop open, I can try removing the buy option itself rather than removing the shop

**Pull request closed without merging**
