### PR TITLE
Removed all API calls to hackclub.com in index.js

### PR DESCRIPTION
**Pull request by Arpan-206**
Removed API requests to `hackclub.com` and replaced them with function calls per Issue #715 .

### CODE REVIEW

**Review by sampoder — CHANGES_REQUESTED** [review]
Perfect! Thank you so much - would it be possible to do it for `gitHubData` as well? 🙌

**Comment by Arpan-206** [comment]
> Perfect! Thank you so much - would it be possible to do it for `gitHubData` as well? 🙌

I did try that is giving errors that I've never seen.

**Comment by sampoder** [comment]
@Arpan-206 don't worry about the errors - those are a separate issue

**Comment by sampoder** [comment]
(for now, just comment out the modified `gitHubData` section)

**Comment by Arpan-206** [comment]
Done

**Comment by Arpan-206** [comment]
(@sampoder I assume this is what you meant)

**Review by sampoder — APPROVED** [review]
LGTM! Appreciate it.

**Comment by ni5arga** [comment]
Cool

**Pull request merged**
