### PR TITLE
Updated title

### PR DESCRIPTION
**Pull request by abbyfischler**
Junior Administrative Engineer

@christinaasquith please approve and merge!

### CODE REVIEW

**Comment by lachlanjc** [comment]
#### 📝 Changed routes:


| [**/team**](https://site-kazm1v9og.hackclub.dev/team) |
|:-:|
|<a href="https://site-kazm1v9og.hackclub.dev/team">Screenshot of /team</a><br /><sup><a href="https://images.weserv.nl?url=https://sjc.microlink.io/1IctRBjWkRQy1GSCMuI8HzuY_-b-gzCnMKx7VDrO23xXMTsQdPYEgqeUNGErvrZwwx7ymkS2Z0n7zef57uNOLw.png">(view full size)</a> |







Commit dfbe97a73ee88ea3dd64d4f403f213a24694950f (https://site-kazm1v9og.hackclub.dev).

**Review by KendallDoesCoding — APPROVED** [review]

**Comment by northeastprince** [comment]
Checks are failing for some reason? Can someone rerun them?

**Comment by bellesea** [comment]
> Checks are failing for some reason? Can someone rerun them?
looks like it's this... it was probably fixed after this PR was made...

Screenshot 2023-04-28 at 1 11 11 PM

**Comment by abbyfischler** [comment]
@bellesea It is showing all green. Can I go ahead and merge?

**Comment by bellesea** [comment]
> @bellesea It is showing all green. Can I go ahead and merge?

yep!!

**Pull request merged**
