### PR TITLE
change role to Engineering, Modreation, & Events and add bio

### PR DESCRIPTION
**Pull request by radioblahaj**

### CODE REVIEW

**Comment by radioblahaj** [comment]
@karamassie is this change ok? I can put it back to how it was before and just add the bio. If the role is too long, how is Community Engineering?

**Review by grymmy — CHANGES_REQUESTED** [review]
Please fix punctuation (spaces after commas).

**Review by grymmy — APPROVED** [review]
lgtm

**Comment by grymmy** [comment]
I am closing this issue due to the recent landing of https://github.com/hackclub/site/pull/1069, which changes the way we program this data unless I am very mistaken.  Please reopen and advocate for the landing of this PR if you feel this was done in error.

**Pull request closed without merging**
