### PR TITLE
Let it snow!

### PR DESCRIPTION
**Pull request by maxwofford**
Force snowing to always be true

Creating this for testing https://github.com/hackclub/site/pull/1056/files

### CODE REVIEW

**Comment by lachlanjc** [comment]
#### 📝 Changed routes:


| [**/**](https://site-e3rr64xss.hackclub.dev/) |
|:-:|
|<a href="https://site-e3rr64xss.hackclub.dev/">Screenshot of /</a><br /><sup><a href="https://images.weserv.nl?url=https://sjc.microlink.io/FpCmR_cyAEW2OR5WXUTlgO8q8uLmOXmfqr4p2YzkhaPzzakTQgVTaaTYDia4qBpLCIBiVRVyDZLsRRU6uUhOZA.png">(view full size)</a> |







Commit b09796b2f3617ffe77308f31260d334b907fa84f (https://site-e3rr64xss.hackclub.dev).

**Comment by lachlanjc** [comment]
I'd recommend using next/dynamic loading to only download the JS for this when it's needed—Easter eggs shouldn't incur performance hits for all visitors

**Comment by grymmy** [comment]
@maxwofford @lachlanjc should this be closed at this point?

**Comment by lachlanjc** [comment]
I'd vote to remove snow permanently from the Hack Club site, unless it's a specific winter project.

**Pull request closed without merging**
