### PR TITLE
Disable Joining Slack as an Adult

### PR DESCRIPTION
**Pull request by sampoder**
Screenshot 2023-02-23 at 12 22 24 AM

cc: @karamassie @maxwofford - do we want to do this?

### CODE REVIEW

**Review by maxwofford — APPROVED** [review]
LGTM!

**Comment by maxwofford** [comment]
Screenshot 2023-02-22 at 13 47 34

**Comment by Arpan-206** [comment]
Isn't it too easy to just put smth else and join anyways? How do we prevent that?

**Comment by maxwofford** [comment]
cc @karamassie

**Comment by bellesea** [comment]
should it be "Our Slack community is for teenagers" instead of "Our Slack community for teenagers"?

**Pull request merged**
