### PR TITLE
Use Polymer to update open roles at Hack Club

### PR DESCRIPTION
**Pull request by exu3**
This PR:

- changes the design of the joblisting card a bit
- job listings are pulled from Polymer

This PR only updates the jobs index page.

### CODE REVIEW

**Comment by lachlanjc** [comment]
#### 📝 Changed routes:


| [**/jobs**](https://site-qhk4o9rqn.hackclub.dev/jobs) |
|:-:|
|<a href="https://site-qhk4o9rqn.hackclub.dev/jobs">Screenshot of /jobs</a><br /><sup><a href="https://images.weserv.nl?url=https://sjc.microlink.io/hVrDW4K-W921sxrp0Qdv8fEIV9eJNCT_38Y_maTN3_-xnbQzsHAkPgKNgcIYUPT1a3aXnyJhtLTDAD_Q5XDqyA.png">(view full size)</a> |







Commit 88d114570f6efb63d8fbe4bd02f739e1b4358b65 (https://site-qhk4o9rqn.hackclub.dev).

**Comment by exu3** [comment]
#### 📝 Changed routes:


| [**/jobs**](https://site-qhk4o9rqn.hackclub.dev/jobs) |
|:-:|
|<a href="https://site-qhk4o9rqn.hackclub.dev/jobs">Screen Shot 2022-10-03 at 10 50 01 PM</a><br /><sup><a href="https://images.weserv.nl?url=https://sjc.microlink.io/JsFHqiUKTHFmtQsrWDTjl6TUer_DH_wCmMytw6Asx493yeF69WH2gKG7eVi7k4NBp-krBCzYNotXsWZE24miTA.png">(view full size)</a> |

**Comment by exu3** [comment]
When there are no open roles: 

Screen Shot 2022-10-03 at 10 56 52 PM

**Review by sampoder — APPROVED** [review]
Looks great to me!

**Pull request merged**
