### PR TITLE
Fixed Security Issue (rel='noopener')

### LINKED ISSUE #944: Security issues by using target="_blank" attribute
Adding rel="noopener" or rel="noreferrer" to your target="_blank" links avoids these issues.

### PR DESCRIPTION
**Pull request by nermalcat69**
Fix #944

### CODE REVIEW

**Comment by nermalcat69** [comment]
i think i gotta fix this never mind

**Comment by malted** [comment]
lgtm in a vacuum; however do you think there's a way to add this to the `Link` Theme UI element?

**Comment by malted** [comment]
People will not remember to add it every time they create a new anchor

**Comment by nermalcat69** [comment]
> lgtm in a vacuum; however do you think there's a way to add this to the `Link` Theme UI element?

yeah i'll do that thing thanks malted 👍🏼

**Pull request closed without merging**
