### PR TITLE
Fix horizontal scroll for mobile on team page

### PR DESCRIPTION
**Pull request by MatthewStanciu**
I was scrolling through the team page on my iPhone and noticed that the font size of the text on one of the titles was causing horizontal scrolling. This PR decreases the font size for smaller screen sizes. This definitely changed many pages since I edited the theme, and I didn't check to see if this change broke anything, but I expect it probably only made things better for smaller screen sizes. Feel free to close or change anything you want though.

Screen Shot 2021-08-29 at 3 20 07 PM
Screen Shot 2021-08-29 at 3 20 13 PM

### CODE REVIEW

**Comment by exu3** [comment]
I think changing the `fontSize` on that specific title might be better because I noticed that changing the theme made the homepage titles look too small on mobile

Changing the theme




Currently

**Comment by MatthewStanciu** [comment]
Thank you for doing the testing that I didn't feel like doing @eilla1 🙏 I just reverted the changes to the theme & updated the font size directly to the 2 headings on the team page

**Comment by lachlanjc** [comment]
#### 📝 Changed routes:


| [**/team**](https://v3-bsbb8m0pk.hackclub.dev/team) |
|:-:|
|<a href="https://v3-bsbb8m0pk.hackclub.dev/team">Screenshot of /team</a><br /><sup><a href="https://images.weserv.nl?url=https://sjc.microlink.io/T1WKLsJ2uwBeBouLabcrChALqIYWw5k2ChyPiY_3dXfw5EGWYGXIEPx_hqbXwE4UGk8kNQuYJ8aG1hgtAhwJVw.png">(view full size)</a> |







Commit 2cbeda66f1b51c418ec2ee710d160b17ea8bd5c7 (https://v3-bsbb8m0pk.hackclub.dev).

**Comment by wahoo-fish** [comment]
wahoo

**Review by sampoder — APPROVED** [review]
Thanks Matthew & Ella! + Wahoo!

**Pull request merged**
