### PR TITLE
Onboard page updates

### PR DESCRIPTION
**Pull request by kognise**

### CODE REVIEW

**Comment by lachlanjc** [comment]
#### 📝 Changed routes:


| [**/onboard**](https://site-8jm4lj07o.hackclub.dev/onboard) |
|:-:|
|<a href="https://site-8jm4lj07o.hackclub.dev/onboard">Screenshot of /onboard</a><br /><sup><a href="https://images.weserv.nl?url=https://sjc.microlink.io/ZdrEtFJa2WnIAOpswD8Vjdk1fDQI655tPnFDbbyPH2N7RBNo4rIeySMyovt_AaUfxJVaY2IV-tJI0nWeFzXqIg.png">(view full size)</a> |







Commit 516a82ce30cc0934b9de4850a8bc187d2e369fbb (https://site-8jm4lj07o.hackclub.dev).

**Comment by radioblahaj** [comment]
Small nitpick from me, can we change the link to the /slack page from the pre-filled reason on the community button to redirect people to https://hackclub.com/slack?event=onboard instead? There's a custom flow if they come from the event query

**Comment by sampoder** [comment]
i think that'd be sick!

**Comment by kognise** [comment]
merging now - i'm gonna go through and implement feedback over the rest of today

**Pull request merged**
