### PR TITLE
Add /wallpapers page

### PR DESCRIPTION
**Pull request by Tiger-The-Cat**
Not sure if there is a protocol for adding a new Hack Club page, so I'm just making a PR.

Notes:
- This is a modified [/stickers](https://hackclub.com/stickers/) page
- We currently don't have any wallpapers, so every image is set to "wallpepper.png". This will change.
   
- For the relevant discussions, see the [hc-wallpapers slack channel](https://hackclub.slack.com/archives/C05NAHPUK38)

Credits:
- [Damian Freeman](https://github.com/Daymeeuhn) for the idea

### CODE REVIEW

**Comment by lachlanjc** [comment]
#### 📝 Changed routes:


| [**/wallpapers**](https://site-ds92z2lpa.hackclub.dev/wallpapers) |
|:-:|
|<a href="https://site-ds92z2lpa.hackclub.dev/wallpapers">Screenshot of /wallpapers</a><br /><sup><a href="https://images.weserv.nl?url=https://sjc.microlink.io/_okwKdsYi76Gxz-k7XmbJoxAbN3aXjPQOVpx2S_DzOsYA_kSJlNnH0GOfehm8eOp7CtuTbHlYU5Qx9TAnmaSOw.png">(view full size)</a> |







Commit 2238e76f8fca0b7a69403947da876840e6915399 (https://site-ds92z2lpa.hackclub.dev).

**Comment by malted** [comment]
Hi! Thanks for opening this; it's a great concept.
I would ask that the styling on the page is completed before we merge this.

Also, I encourage you to gather more wallpapers! Merging into main with missing/placeholder assets isn't a good idea.

**Comment by Tiger-The-Cat** [comment]
Thanks! I definitely agree about the lack of wallpapers, what other styling would you suggest?

**Comment by malted** [comment]
Hey! This slipped past me. Left some comments on the Vercel preview deployment re: styling.
Since the crux of the issue with this PR is lack of wallpapers, I'll close this for now!
I love this idea and really want to see this be a thing; definitely open another when you have some wallpapers with which to populate the page!

**Pull request closed without merging**
