### PR TITLE
removed wonderland

### PR DESCRIPTION
**Pull request by gaurav-archive**

### CODE REVIEW

**Comment by NalinPlad** [comment]
maybe we wait till we replace with something

**Comment by NalinPlad** [comment]
like another hackathon

**Comment by lachlanjc** [comment]
#### 📝 Changed routes:


| [**/**](https://site-ijr2i5g5s.hackclub.dev/) |
|:-:|
|<a href="https://site-ijr2i5g5s.hackclub.dev/">Screenshot of /</a><br /><sup><a href="https://images.weserv.nl?url=https://sjc.microlink.io/hVlLPMg7aZo84Cnc69PFYmDmDwKqulej-i2IoLmZQN7O_FR-AsWb6T6fMkLy7fM5q6FW8nkiwv_CMF3uv0rXjA.png">(view full size)</a> |







Commit b2b1a507a963dcc66435493b795b9d958068bf50 (https://site-ijr2i5g5s.hackclub.dev).

**Review by JosiasAurel — APPROVED** [review]
lgtm

**Comment by gaurav-back-up** [comment]
ty! please merge

**Pull request merged**
