### PR TITLE
Opinionated Changes to the Bank Apply Form

### PR DESCRIPTION
**Pull request by sampoder**

### CODE REVIEW

**Comment by lachlanjc** [comment]
#### 📝 Changed routes:


| [**/bank/apply**](https://v3-arkpakm8d.hackclub.dev/bank/apply) |
|:-:|
|<a href="https://v3-arkpakm8d.hackclub.dev/bank/apply">Screenshot of /bank/apply</a><br /><sup><a href="https://images.weserv.nl?url=https://sjc.microlink.io/nXGmxcDOEoQJ8IPlKFKB4QDwbN2cgmf4GKSk6C96dXRm3Lk0Cqff72xZsZE6vgq4zkLRYkmCkU_TtQR2jA8Emg.png">(view full size)</a> |







Commit 8b6c255f895c65ce41fbd5bff1cabfcadd61a5b5 (https://v3-arkpakm8d.hackclub.dev).

**Comment by sampoder** [comment]
I also thought, could we remove the mailing address section? Like is that used anywhere?

**Review by exu3 — APPROVED** [review]
Thanks! I like these changes. I think the background looks great.

Re: mailing address fields. I think they are used to send "welcome" gifts to orgs that join Bank sometimes. I'm not completely sure though; I'll check with Mel & Liv.

**Comment by MelSmith104** [comment]
i love this! and yes the mailing address is to send out gifts :)

**Pull request merged**
