### PR TITLE
Update Bank stats

### PR DESCRIPTION
**Pull request by exu3**
This PR updates the fallback on the Bank stats component and uses the event count from the stats API endpoint, but that part is a little jank https://github.com/hackclub/site/pull/386#issuecomment-1077082791.

### CODE REVIEW

**Comment by exu3** [comment]
This feels a bit jank because it flashes the fallback before displaying the value from the API.

https://user-images.githubusercontent.com/72365100/159843698-2e9610f3-4df5-43b6-b5f4-14a96b5ca526.mov

**Comment by sampoder** [comment]
Could we prefetch data in getStaticProps?

**Comment by sampoder** [comment]
I think getStaticProps needs to be in the main page file

**Comment by lachlanjc** [comment]
#### 📝 Changed routes:


| [**/bank/\[type\]**](https://v3-cs5yswkmx.hackclub.dev/bank/[type]) |
|:-:|
|<a href="https://v3-cs5yswkmx.hackclub.dev/bank/[type]">Screenshot of /bank/[type]</a><br /><sup><a href="https://images.weserv.nl?url=https://sjc.microlink.io/cFdAhuM_3NiNVFB4njiUNhasCpAfOEaT4AEW58o2zE0VLsm_WKE3HzedXDjqeKoPv1virWELImfBZwKBOVG0Kw.png">(view full size)</a> |







Commit a0f55a26072b9221cb1688c50340d6bfed0bd1ef (https://v3-cs5yswkmx.hackclub.dev).

**Comment by exu3** [comment]
> I think getStaticProps needs to be in the main page file

Ah thanks Sam! It should work now.

**Review by sampoder — APPROVED** [review]
amazing!

**Pull request merged**
