### PR TITLE
Show confetti if raised >10m in a week

### PR DESCRIPTION
**Pull request by faisalsayed10**

### CODE REVIEW

**Comment by maxwofford** [comment]
Keep in mind raised is in cents, so this will trigger at $100k per week (still pretty large)

**Comment by faisalsayed10** [comment]
ooh i see, what about $50k?

**Comment by maxwofford** [comment]
I like the feature, but I think I'd be confused without context that $50k has been raised– do we say that anywhere on the site?

**Comment by faisalsayed10** [comment]
Hmm I agree. We'd have to show it somewhere (but where?)

**Comment by bellesea** [comment]
@faisalsayed10 what about a small notification pill on the top right hand corner that says we've raised more than xyz this week?

**Comment by faisalsayed10** [comment]
sure, that's a good idea!

**Comment by bellesea** [comment]
> sure, that's a good idea!

awesome, are you interested in implementing that? or i could do it?

**Comment by faisalsayed10** [comment]
@bellesea please feel free to do it, I've been swamped with a lot of other stuff, so it'll take time for me.

**Pull request closed without merging**
