### PR TITLE
Add In-N-Out sticker

### PR DESCRIPTION
**Pull request by Tiger-The-Cat**
Approved by @PellMellKid.

### CODE REVIEW

**Comment by malted** [comment]
Ooh! Have you got these printed?

**Comment by Tiger-The-Cat** [comment]
Not yet! I'm not sure if they're in HC circulation.

**Comment by aramshiva** [comment]
@malted is there an update on this?

**Comment by malted** [comment]
Sorry for letting this sit for so long! I love the sticker.

**Comment by Tiger-The-Cat** [comment]
Thank you, @malted!

**Pull request merged**
