### PR TITLE
Vitalik AMA Standby Site

### PR DESCRIPTION
**Pull request by bellesea**
Hi! I can't figure out how to squash my previous commits ( they don't do anything lol ), if anyone has advice, would really appreciate it :)

Thanks!

### CODE REVIEW

**Comment by sampoder** [comment]
we can squash when we merge

**Comment by sampoder** [comment]
Thoughts on making it `/vitalik`?

**Comment by bellesea** [comment]
> Thoughts on making it `/vitalik`?

works for me :) @maxwofford ?

**Comment by maxwofford** [comment]
Go for it. Let's bias for merging in it's current form b/c the AMA is coming up soon-- it looks really good.

**Comment by sampoder** [comment]
@bellesea would you be cool with me merging?

**Comment by bellesea** [comment]
> @bellesea would you be cool with me merging?

yep! thanks :)

**Review by sampoder — APPROVED** [review]

**Pull request merged**
