### PR TITLE
add cpu badge

### PR DESCRIPTION
**Pull request by bellesea**

### CODE REVIEW

**Review by sampoder — APPROVED** [review]
Let's do it

**Comment by lachlanjc** [comment]
#### 📝 Changed routes:


| [**/**](https://site-4ioyjysjs.hackclub.dev/) |
|:-:|
|<a href="https://site-4ioyjysjs.hackclub.dev/">Screenshot of /</a><br /><sup><a href="https://images.weserv.nl?url=https://sjc.microlink.io/7pWY1-BldopFj4u2z9WVYkMKNWedxAQdwfHNkQObJ4oJIWWeUyLV0y_1HGlvu_iuzvHKiGRgYgIEMU7k5c_g_g.png">(view full size)</a> |







Commit 539600d5bfb5ca5daf3b164f9ce23a0410dbd5dd (https://site-4ioyjysjs.hackclub.dev).

**Review by kognise — CHANGES_REQUESTED** [review]
I think the text should be a lot smaller, as is it takes up a lot of space and looks meh. Shorter text would also be more consistent with the other badges. I can take a shot at writing copy at some point before the Launch.

**Comment by bellesea** [comment]
agreed! thanks :) i took another pass and edited it :) a pass from you would be great too!

**Comment by aramshiva** [comment]
@kognise is there any update on this?

**Comment by sampoder** [comment]
The announcement spot has been replaced with Onboard rn. In a separate PR, it'd be nice to add a card to the carousel (if we haven't already)

**Pull request closed without merging**
