### PR TITLE
Add signed-out view to Arcade Shop

### PR DESCRIPTION
**Pull request by skyfallwastaken**
Screenshot:
image

### CODE REVIEW

**Comment by skyfallwastaken** [comment]
Note that I had to use hardcoded items for testing as I don't have access to the Airtable

**Comment by maxwofford** [comment]
This is awesome @SkyfallWasTaken! I just approved deploy. There are a bunch of individual formatting changes and things like `==` -> `===` in this that aren't related to the page you're adding. Can you roll those back so I can merge?

**Comment by lachlanjc** [comment]
#### 📝 Changed routes:


| [**/arcade**](https://site-7go8g97ic.hackclub.dev/arcade) | [**/arcade/shop**](https://site-7go8g97ic.hackclub.dev/arcade/shop) |
|:-:|:-:|
|<a href="https://site-7go8g97ic.hackclub.dev/arcade">Screenshot of /arcade</a><br /><sup><a href="https://images.weserv.nl?url=https://sjc.microlink.io/TtuP1gOqt_4gujQzPGFUifvwD6WnMG-2RIdd9rGQxGDJPU4W0YJUcS5LRB0dNK9h5uGdnuN3oBC1isFqeZd6tA.png">(view full size)</a> |<a href="https://site-7go8g97ic.hackclub.dev/arcade/shop">Screenshot of /arcade/shop</a><br /><sup><a href="https://images.weserv.nl?url=https://sjc.microlink.io/wkMQjokbkh4u36VqeInT3GkdAnY1xDYaZKlU6ghQ9EMxb97WCOE2OPCA3OsCoNocZeFZbrEZT72SWmH7m2Zp2Q.png">(view full size)</a> |



And 2 other routes:
- [**/api/arcade/hack-hour/inventory**](https://site-7go8g97ic.hackclub.dev/api/arcade/hack-hour/inventory)
- [**/api/arcade/shop**](https://site-7go8g97ic.hackclub.dev/api/arcade/shop)



Commit 7c38e6d56c2246789189f978f33ccbc350b6c0f5 (https://site-7go8g97ic.hackclub.dev).

**Comment by skyfallwastaken** [comment]
@maxwofford just removed the `===` and formatting stuff, lmk if there's anything I missed

**Pull request merged**
