### PR TITLE
New Bin website!

### PR DESCRIPTION
**Pull request by aaronw-dev**

### CODE REVIEW

**Comment by aaronw-dev** [comment]
:(

**Comment by aaronw-dev** [comment]
SOMEBODY MERGE THIS

**Comment by grymmy** [comment]
@aaronw-dev is merging this still very important to you?  There was another PR I reviewed earlier this afternoon that seemed identical - if this is a dupe of that (or that or this), plz close the duplicate...

**Comment by aaronw-dev** [comment]
@grymmy this is an old PR, my bad. Closing now.

**Pull request closed without merging**
