### PR TITLE
Add design awards stickers

### LINKED ISSUE #528: Add More Stickers!
- [x] Assemble Logo Sticker
- [x] Hackers, assemble!
- [x] Bank Card
- [x] Bank Long Sticker (Light Mode)
- [x] Bank Long Sticker (Dark Mode)
- [x] Bank Logo (Dark Mode)
- [x] Hack Club Design Awards Sticker
- [x] Sprig Orpheus
- [x] Sprig Sticker Sheet
- [x] Zephyr Sticker
- [x] Orpheus sledding

These are just the ones that I remember, there are probably a bunch more. The Sprig ones might not be final.

### PR DESCRIPTION
**Pull request by exu3**
Helps fix #528

### CODE REVIEW

**Review by sampoder — APPROVED** [review]
love it! I've got a slightly different Figma sticker, any idea where that came from?

**Comment by exu3** [comment]
> I've got a slightly different Figma sticker, any idea where that came from?

Interesting, could you send me a picture?

**Comment by maggie-j-liu** [comment]
mine is different as well! seems to be more polished... (and my adobe one is green & black)
image

**Comment by exu3** [comment]
My bad, I exported the wrong Figma sticker, fixed in 41786f41c66a71ebc04a847b25b228d671e66374

For the Adobe stickers, there are 7 different variants, but I'm not sure we should upload all of them to this page?
Screen Shot 2022-08-26 at 12 37 01 AM

**Pull request merged**
