### PR TITLE
Sprig Section Redesign on `/donate`

### PR DESCRIPTION
**Pull request by sampoder**
Screenshot 2022-08-18 at 4 00 09 PM

### CODE REVIEW

**Comment by lachlanjc** [comment]
#### 📝 Changed routes:


| [**/donate**](https://site-3ph29kxfd.hackclub.dev/donate) |
|:-:|
|<a href="https://site-3ph29kxfd.hackclub.dev/donate">Screenshot of /donate</a><br /><sup><a href="https://images.weserv.nl?url=https://sjc.microlink.io/3fcdMMHT2E24ovISpGz2BluPbiIt846W29ZLpdvXmWSFyXeMBMbc387LOI01HUvM-AR4RaI6nf5di1W_omUBtA.png">(view full size)</a> |







Commit e19ccc20fb96996fe3a34da0f266ff650e3077a9 (https://site-3ph29kxfd.hackclub.dev).

**Review by bellesea — COMMENTED** [review]
This looks awesome!! Thinking about how we could add wording that mentions playing games built by their friends and other teenagers too? cuz you can share your game link for other people to download... what do you think?

**Comment by sampoder** [comment]
I think that's a nice idea! My focus was more on the structure than copy but feel free to add :D

**Review by maxwofford — APPROVED** [review]
I'm happy with this going in as it is! Future additions can be in another PR

**Pull request merged**
