### PR TITLE
Added UI in shop to show if an Item is Limited with Stock

### PR DESCRIPTION
**Pull request by aksinghania**
Screenshot Preview

Screenshot 2024-06-21 at 11 10 43 PM

Added the above UI, also checked and tested to ensure the code works by using shop.json from the hack club.site website's (hardcoded data)

This addresses #1245

### CODE REVIEW

**Comment by maxwofford** [comment]
This looks amazing @aksinghania! could you hide the label on quantities over 100? we have some items with lots of stock and it doesn't really matter that it's a limited quantity
Screenshot 2024-06-21 at 15 18 24

**Comment by aksinghania** [comment]
Sure, Working on it!

**Comment by aksinghania** [comment]
Done!

**Comment by maxwofford** [comment]
@aksinghania this is great but double check your casing for the variable name!

**Comment by maxwofford** [comment]
Screenshot 2024-06-21 at 15 49 43
A little bit of overlap in here!

**Comment by aksinghania** [comment]
Working on the overlay problem!

> @aksinghania this is great but double check your casing for the variable name!

Got it, I will switch to camel Case

**Comment by maxwofford** [comment]
I'm merging this now because it's so great, but throw those 2 fixes up in another PR!

**Pull request merged**
