### PR TITLE
Redesigned slack page!

### PR DESCRIPTION
**Pull request by tobyab**

### CODE REVIEW

**Comment by lachlanjc** [comment]
#### 📝 Changed routes:


| [**/slack**](https://site-71888xyoq.hackclub.dev/slack) |
|:-:|
|<a href="https://site-71888xyoq.hackclub.dev/slack">Screenshot of /slack</a><br /><sup><a href="https://images.weserv.nl?url=https://sjc.microlink.io/CQgl7EPS4_SmRJFo5ZThJh5NowkDeUhOSZ5awC6mbyAIulxYRt4lygHjtvTVzAc1eeCFD51RMbbQMm9fakY8fA.png">(view full size)</a> |



And 2 other routes:
- [**/api/channels/get**](https://site-71888xyoq.hackclub.dev/api/channels/get)
- [**/api/join**](https://site-71888xyoq.hackclub.dev/api/join)



Commit f65cabd971a0397d40104fc7c9f4cc3a0cefee59 (https://site-71888xyoq.hackclub.dev).

**Comment by maxwofford** [comment]
Hey @tobyab! Great effort on working through the design. Couple notes from reviewing this:

Screenshot 2024-01-26 at 16 33 28

- Testimony feels unbalanced because the quotes are big and bold, but the attribution is really small and thin


Screenshot 2024-01-26 at 16 35 33

- This section is vertically taller than it needs to be for the image, making the "There's a whole new world to discover" kinda float on the left. It doesn't seem like it should take up the page vertically
- "I'm ready to join" is really small and feels out of place due to the imbalance.


Screenshot 2024-01-26 at 16 35 48

- The carousel steals mouse scrolling
- The cards aren't vertically centered
- the arrows on the bottom left are just sitting there. Should they be centered? Padded by the edge?
  - the hard dark color of the arrows is a little out of place with how subtle the other color changes on the page are

**Comment by tobyab** [comment]
Hey Max!! I've made some changes to the bottom section, making the final bento take up less vertical space, and have changed the font size on the quoter's names to make a bit more sense. What are your thoughts on this? (P.S will continue squashing bugs w/ the carousel. It's not very well optimised right now)
image
image

**Comment by tobyab** [comment]
Hey @maxwofford! I've worked a bit more on the carousel, and it's better optimised now, what're your thoughts?

**Comment by tobyab** [comment]
Will move to a new pr!

**Pull request closed without merging**
